### PR TITLE
Use grid of active station location for distance calculations

### PR DESCRIPTION
**Pull request by phl0**
This fixes https://github.com/wavelog/wavelog/issues/766

### CODE REVIEW

**Review by AndreasK79 — APPROVED** [review]

**Comment by phl0** [comment]
Added function to update distance information for all QSOs. Could you please re-check @AnreasK79?

**Comment by phl0** [comment]
Added function to update distance information for all QSOs. Could you please re-check @AndreasK79?

**Comment by phl0** [comment]
I think we have an issue here with all those functions in country files section as they update *all* QSOs instead of only the ones for the current user. Needs investigation and will be handled separately.

**Comment by phl0** [comment]
> Needs investigation and will be handled separately.

Handled in https://github.com/wavelog/wavelog/issues/769.

**Comment by int2001** [comment]
Tested and works:
Idea: Can we add a spinner / lock for the button, since this is a long-running operation and the admin can't see if there's something happening in the BG?

**Comment by phl0** [comment]
I will refactor the htmx stuff separately. Merging the current state.

**Comment by phl0** [comment]
Spinner stuff to be handled in https://github.com/wavelog/wavelog/issues/771.

**Pull request merged**
