### PR TITLE
[INSTALLER] Next generation of the Wavelog Installer

### LINKED ISSUE #629: qrz.com password does not get encoded during installation
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the discussions area**

**Describe the bug**

Password of qrz.com accepts chars that result in a broken installation

**Version Information**
We need some information about your versions. You can get all Information in the Admin > Debug Menu

- OS:               Debian 12
- Wavelog:          1.7 (current git) 
- Server Software 	Apache
- PHP Version 	8.2.20 OK
- MySQL Version 	10.11.6-MariaDB-0+deb12u1
- Codeigniter Version 	3.2.0-dev

Hint: it would be nice to have this as a ready-to-copy block in the debug menu

**Steps to Reproduce**

1. install wavelog and start installer
2. enter qrz.com credentials containing a '  (single quote) 
3. wavelog hangs after the installer really starts
4. find error in Apache error.log like:

... AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected identifier "D" in /var/www/html/wavelog/application/config/config.php on line 46; PHP message: PHP Parse error:  syntax error, unexpected identifier "D" in /var/www/html/wavelog/application/config/config.php on line 46'

**Expected Behavior**
Either do not accept passwords or better escape them accordingly

### PR DESCRIPTION
**Pull request by HB9HIL**
First I just wanted to fix some known bugs in the installer after the big Frontend Remake in #37 

But I wanted to improve the backend aswell and give the user a better feedback during the process as the whole database stuff can take a while. So I rebuilt the backend of the installer and added some frontend stuff for better response to the user. 

Improvements:

- Fixed some bugs regarding language
- Save inputs in localStorage to don't loose all the entered data in case of a page reload
- Finally added the checklist on the last page
- Added a second page which shows the current step of the installation for better UX

Work in Progress:

- [x] Readd POST Validation for server side validation
- [x] Better Error Handling if one install step fails
- [x] Fix $browser_language fallback
- [x] Fix #629 
- [x] Fix Warning in user Form (red instead yellow)
- [x] nginx detection by @phl0 
- [x] get rid of flag cdn

image

### CODE REVIEW

**Comment by HB9HIL** [comment]
@int2001 Docker tested successfully

**Comment by HB9HIL** [comment]
Todo:

- [ ] Add in database check if database is empty or
not

**Review by AndreasK79 — APPROVED** [review]

**Comment by AndreasK79** [comment]
@HB9HIL great work. In my eyes, this is ready to be merged now!

**Comment by HB9HIL** [comment]
@phl0 This will be a candidate for a sqash merge 😆

**Comment by phl0** [comment]
> @phl0 This will be a candidate for a sqash merge 😆

As you like. Approved now from my end.

**Review by phl0 — APPROVED** [review]
Installation on Debian 12 still working fine. ngnix settings detector code also working and showing the warning if setting is wrong.

**Review by int2001 — APPROVED** [review]
(Re-)Tested latest Version of this PR with various docker-setups.
Works.

Very very nice contribution. First impression now like installing absolute pro-soft ;)

**Pull request merged**
