### PR TITLE
Spelling fixes in german locale

### PR DESCRIPTION
**Pull request by dn4bs**
This patch tries to fix a a most of the misspelled compound nouns, mostly by adding hyphens. There are a also a very few trivial message rewrites.

### CODE REVIEW

**Comment by phl0** [comment]
Just to let you know we have an excellent platform for doing translations. See:

https://translate.wavelog.org/

**Comment by dn4bs** [comment]
> https://translate.wavelog.org/

Which I'll probably use next time. Right now I'm more interested in learning about github and pull requests.
I hope the patch is not too unwieldy for inclusion…

**Comment by phl0** [comment]
I will fix the issues. Next time please:

- use the current dev branch to create your feature branch (not master)
- use weblate for translations

In any case your contributions are very welcome.

**Comment by dn4bs** [comment]
> I will fix the issues. Next time please:
> 
>     * use the current dev branch to create your feature branch (not master)

I think I did. But then merged my feature branch into the master branch of my fork.
I'll try not to do this next time and 
> 
>     * use weblate for translations
for translations.

> In any case your contributions are very welcome.

Thank you!

**Review by phl0 — APPROVED** [review]
German updated and ok now :)

**Review by HB9HIL — APPROVED** [review]

**Pull request merged**
