### PR TITLE
[User] Insert default for map icons when creating a new user

### PR DESCRIPTION
**Pull request by AndreasK79**
Yet another thing making life easier when creating new users.
Setting default icons for map when a new user is created.

### CODE REVIEW

**Comment by int2001** [comment]
got an error on a fresh user within Account-Settings, Map-Icon-Setup (within dropdown). PHP tells: `Undefined variable $user_map_gridsquare_show` at User-edit-View.

PS: Should consider setting "Default-QSL-Method" as well, what do you think?

**Comment by abarrau** [comment]
Hello all, 
can i propose an other way ? 
we can allow icon map options directly on create user page. 
i speak about that with @HB9HIL few time ago. 
perhaps is better ? 
i can propose something this week if you are ok
73

**Comment by AndreasK79** [comment]
Hi @abarrau. Sure, it was just to make it easier when creating a new user :)

You can add to "Create user" page. And when you do, set default values, so that the user do not have to choose anything in the page if the user does not want to.

**Comment by phl0** [comment]
But it doesn't harm to have default values even if it can be chosen upon user creation. Just in case ...

**Comment by abarrau** [comment]
hi, 
i this it's my previous proposal need lot of changes. 
the user_model add (and edit) function has a strange code  ... so a simple action, need to add lot of change ...
so lot of work (with risk) for "little" profit...

i propose we change nothing about that, and @AndreasK79 you can finish this PR ... sorry for delay

**Comment by AndreasK79** [comment]
@abarrau thanks, I understand. Will update and merge later.

**Review by phl0 — APPROVED** [review]
Works as expected. Good stuff.

**Pull request merged**
