### PR TITLE
DXCC Dropdown

### PR DESCRIPTION
**Pull request by HB9HIL**
"multiselect" Library in dxcc dropdown (without multiselect). 

Ability to filter DXCC

Collab work with @AndreasK79 

image

### CODE REVIEW

**Comment by HB9HIL** [comment]
Comment: Still needs some CSS fixes to match themes and surrounding elements

**Comment by HB9HIL** [comment]
For documentation: https://davidstutz.github.io/bootstrap-multiselect/#configuration-options

**Comment by HB9HIL** [comment]
At the moment only in Logbook Advanced, but can be easily added in other places aswell

**Review by AndreasK79 — APPROVED** [review]

**Comment by AndreasK79** [comment]
Tested working. Easier to choose when you don't have to scroll through everything!

**Pull request merged**
