### PR TITLE
#803 - Add SFLE JS errors

### LINKED ISSUE #803: Report basic errors in Simple Fast Log Entry (SFLE) right away
**What Feature is Missing?**
When you use the FLE functionality for logging QSO's (as I do when I am on portable) and you do not specify the basic information, like band or mode, the error is reported to you when "Save in Wavelog" button is pressed. It would be cool to know this information up-front, even before you start the logging, just to improve the UX a little. Especially, when the source code is ready for it (but there is a little bug in it, I plan to inform the upstream source author OK2CQR about this and fix it on his side too).

**Steps to Reproduce**
1. Go to 'QSO > Simple Fast Log Entry'
2. Paste following to the textarea: 
ok12asd
adas3sda
3. See that no error is displayed, even though the basic info about the band/mode/time is missing

**Expected Behavior**
Errors should be presented to user right away to know he should add the basic data

**Why is This Feature Important?**
I believe this would improve the FLE entry's UX

**Is This Feature Personal or Beneficial to Others as Well?**
I hope so :)

**Screenshot of the current state**
Screenshot 2024-08-25 at 8 40 19

**Screenshot of the proposed state**
Screenshot 2024-08-25 at 8 40 33

**Additional Context**
I have already fixed it on my side. If you think this is beneficial to others I will submit a PR.

### PR DESCRIPTION
**Pull request by filipmelik**
Closes #803

### CODE REVIEW

**Review by HB9HIL — CHANGES_REQUESTED** [review]
Thank you very much for your PR :) 

Unfortunately I see some issues here

1. Due to the new `<div>` in `index.php` Line 130 the screen resizing does not work properly and the lower button bar is too low. So a scroll is necessary to see the full button bar. 
DEV
image
PR
image
2. Similar UI issue when error's are displayed
image
3. A click on "Clear logging session" should hide the warnings.

The resizing of the whole frontend is done in function `resizeElements()` in `assets/js/sections/simplefle.js`.  It is built to only make a scroll in the QSO table necessary.  To solve this you could consider resizing the `textarea` instead expanding the view to south. If you need help here let me know :)

**Comment by HB9HIL** [comment]
@filipmelik You created your PR branch `filipmelik:803-SFLE-js-errors` based on `master`. Please create PR branches based on `dev` to avoid conflicts. 

To update this branch please click on "Update branch"
image
or perform in your CLI
```bash
git fetch upstream
git merge upstream/dev
git push
```

**Comment by HB9HIL** [comment]
> @filipmelik You created your PR branch `filipmelik:803-SFLE-js-errors` based on `master`. Please create PR branches based on `dev` to avoid conflicts.


I noticed that because I fixed an issue with cookie prefixes in dev branch which is not included in your PR and crashed my dev installation 😆

**Comment by filipmelik** [comment]
Sorry for that and thanks for review :) 

Clearing errors on logging session is easy and pushed. But I have to admit that I am kind of lost with the rest of UI stuff. I am not sure if it would not be much faster that you could possibly fix it, since I am not FE guy at all. If not, I will probably need some hints on how to proceed here. 👨‍🎓

**Comment by HB9HIL** [comment]
> Sorry for that and thanks for review :)
> 
> Clearing errors on logging session is easy and pushed. But I have to admit that I am kind of lost with the rest of UI stuff. I am not sure if it would not be much faster that you could possibly fix it, since I am not FE guy at all. If not, I will probably need some hints on how to proceed here. 👨‍🎓

No Problem :) 

Repull and test (make sure you clear the cache)

https://github.com/wavelog/wavelog/pull/804/commits/dc0138b7189413bba100b45b2a879527824172e9 should fix the main UI resizing

**Comment by HB9HIL** [comment]
PS: The whole UI is not perfect but I think this is okay xD (I'm no UI expert either haha)

**Comment by filipmelik** [comment]
Checked and LGTM, thanks for the fix! 
Only thing  I have noticed is that mobile display of QSO table is somehow too big. However it is another issue for another PR :)

**Comment by HB9HIL** [comment]
> Checked and LGTM, thanks for the fix! Only thing I have noticed is that mobile display of QSO table is somehow too big. However it is another issue for another PR :)

Yep. Mobile is a complete different story. There are a lot of constructions sites for mobile operation. In my personal opinion we should consider an app with API access instead painfully try to fix all the CSS adventures..

**Review by HB9HIL — APPROVED** [review]
works now :)

**Pull request merged**
