### PR TITLE
[eQSL] only locations with a eQSL nickname should be displayed

### PR DESCRIPTION
**Pull request by dg0tm**
only locations with a eQSL nickname should be displayed in the dropdown under eQSL Import

### CODE REVIEW

**Comment by phl0** [comment]
Not sure about this one tbh. The download link to the eqsl.cc inbox obviously downloads the entire eQSL inbox anyway. So it probably contains more than just the QSOs on the profiles linked to eQSL nicknames?!

**Comment by int2001** [comment]
Agree with @phl0 - it doesn't have any effect since eQSL isn't taking care of that.
Would only affect the UI, but not the logic. 
perhaps we should remove the station-chooser from eQSL completly and show the import only if there's at least one Station-location with eQSL-Nicknames set?

**Comment by dg0tm** [comment]
please see #73

and I believe the downloaded inbox only contains QSLs for or from the selected nickname. We were always confused when QSOs updated out of scope...

**Comment by int2001** [comment]
> and I believe the downloaded inbox only contains QSLs for or from the selected nickname. We were always confused when QSOs updated out of scope...

i just tried that. created a station_location with the same CALL but a different Nickname (fun fact: one that doesn't exist at eQSL). eQSL-Endpoint is downloading/fetching ALL eQSLs and doesn't take care of the Nick when fetching the eQSLs. The "Nickname" is passed to eQSL, but eQSL ignores it

**Comment by HB9HIL** [comment]
error

There is missing an error handler if no station has an eQSL Nickname

**Review by HB9HIL — CHANGES_REQUESTED** [review]
please add an error handler if no station has an eQSL Nickname

**Review by int2001 — APPROVED** [review]
works

**Comment by HB9HIL** [comment]
> Okay, I took a first look at it and it is not triggered by this patch.
> 
> Should I patch this in another PR or with this one?

You cann add the error handler in this PR

**Comment by dg0tm** [comment]
quick & dirty patch via flash message

i also add 2 lines for better knowledge off witch button belongs to which function at all

**Comment by dg0tm** [comment]
eQSL-Nickname_not_defined

**Comment by dg0tm** [comment]
eQSL-usability

by switching the order, it is much more intuitive

**Review by HB9HIL — APPROVED** [review]

**Pull request merged**
