### PR TITLE
fixes buggy modal dialog

### PR DESCRIPTION
**Pull request by HB9HIL**
replacement for #914

### CODE REVIEW

**Review by phl0 — CHANGES_REQUESTED** [review]
Fixes the errror in browser view but breaks the click action in fullscreen view ... :(

**Comment by HB9HIL** [comment]
> Fixes the errror in browser view but breaks the click action in fullscreen view ... :(

All issues solved I guess. @phl0 and @AndreasK79 please check. 

I created two new functions in common.js which can be used again if this issue appears somewhere else aswell. 

I also added a dark background additionally to make the modal in the map more visible in fullscreen mode. This adds two backgrounds in the normal view which makes it likely darked. But imho something we can live with.

**Comment by HB9HIL** [comment]
@phl0 

PS: Your code 

```js
        if ($('.modal-dialog')[0]) {
		return;
	}
```

was necessary aswell as the onMapClick() stuff differs a bit from the standard leaflet behaviour

**Review by phl0 — APPROVED** [review]
This works nicely now. Closing https://github.com/wavelog/wavelog/pull/914 in favor of this. Tnx fer digging in.

**Review by AndreasK79 — APPROVED** [review]

**Pull request merged**
