### PR TITLE
Long Path Fixes

### PR DESCRIPTION
**Pull request by HB9HIL**
There are some more places where distances are calculated

Test:
- LBA Mapping -> Distance is shown in the little map modals
- LoTW Update (via File) -> maybe @phl0 can check that
- Logbook Controller methods `distance()` (not in use?) and `bearing()` (is in use but does not need any further adjustment
- Regtest1 Format
- QSO View VUCC Multis Distance

### CODE REVIEW

**Comment by phl0** [comment]
LoTW does not handle/care about distances. So we will not retrieve that info from LoTW files.

**Comment by phl0** [comment]
OK misunderstood. It is just re-calculating on LoTW import. Will test.

**Review by int2001 — APPROVED** [review]
tested:
- Logging
- Editing
- Update via "Show distances"
- Update via "Admin-Menu"

works.

not able to test it in reality, because i don't fill in SP or LP. But from the Test-POV it looks okay to me.

**Comment by phl0** [comment]
> @phl0 did you test

Planned for tonight. :)

**Comment by phl0** [comment]
Fix in https://github.com/HB9HIL/wavelog/pull/117. You cannot use $data['COL_ANT_PATH'] in line 3627/3630 as $data was unset before. So it would be null in any case leading to distance always being calculated as SP.
Instead we have to pull it from the QSO we previously looked up to confirm.

**Review by phl0 — APPROVED** [review]
LoTW Import now works correctly.

**Pull request merged**
