### PR TITLE
Resized droplist for station location name and contest name 

### PR DESCRIPTION
**Pull request by R1BLH**
Resized droplist for station location name and contest name to full width on pages Import/Export ADIF and eQSL Import.

Before resize the width of the droplist was less then station location name width:
изображение

After resize it looks better. IMHO
изображение

### CODE REVIEW

**Review by phl0 — CHANGES_REQUESTED** [review]
To be honest: 100% width makes the form look a bit odd in my eyes. Maybe we can stretch it to 50%? Would that suit your case?

**Comment by R1BLH** [comment]
> To be honest: 100% width makes the form look a bit odd in my eyes. Maybe we can stretch it to 50%? Would that suit your case?

Done. View with 50% width is still better than 20%. :)
изображение

Do you have any idea how to increase the width of the file selector to 50% as well?

**Comment by phl0** [comment]
> Do you have any idea how to increase the width of the file selector to 50% as well?

Will have a look.

**Comment by phl0** [comment]
Like that?

image

**Comment by R1BLH** [comment]
> Like that?
> 
> image

Yes! Perfectly.

**Comment by phl0** [comment]
Here is the code:

```
diff --git a/application/views/adif/import.php b/application/views/adif/import.php
index b9dd0a089..a6469b975 100644
--- a/application/views/adif/import.php
+++ b/application/views/adif/import.php
@@ -75,7 +75,9 @@
                             } ?>
                        </select>
                        <label class="visually-hidden" for="inlineFormInputName2"><?= __("ADIF File") ?></label>
-                        <input class="form-control mb-2 me-sm-2 w-auto" type="file" name="userfile" id="userfile" size="20" />
+                        <div style="margin-top: 1em; width: 50%">
+                        <input class="form-control mb-2 me-sm-2" type="file" name="userfile" id="userfile" />
+                        </div>
 
                         <div class="mb-3 row">
                             <div class="col-md-10">
```

**Comment by R1BLH** [comment]
> <div style="margin-top: 1em; width: 50%">
> +                        <input class="form-control mb-2 me-sm-2" type="file" name="userfile" id="userfile" />
> +                        </div>

Code inserted.  Thank you!

**Comment by HB9HIL** [comment]
@phl0 and @R1BLH 

Why not using the `w-auto` class by bootstrap?

**Comment by R1BLH** [comment]
It's better then fixed width!

**Comment by phl0** [comment]
I think @HB9HIL's PR in https://github.com/R1BLH/wavelog/pull/1 is a good way to have wider fields and also working on mobile. So if you merge that PR to your branch for this PR I will merge this one uptream.

**Pull request merged**
