### PR TITLE
Delete all fragments which belongs to a user upon deleting

### PR DESCRIPTION
**Pull request by int2001**
While testing on my instance i recognized a lot of old QSOs and other fragments where still in Database active.
In preparation of activating contraints somewhere in the future, we should delete everything which belongs to the User.

Affected Actions:
- Delete User (should delete everything from the user: OQRS, Certs, QSOs, eQSLs, QSLs, bandx, stations, logbooks, etc.)
- Delete Station-Location (should delete everything from the station: OQRS, QSOs, eQSLs, QSLs)

### CODE REVIEW

**Review by HB9HIL — APPROVED** [review]

**Comment by HB9HIL** [comment]
Works great :)

**Comment by phl0** [comment]
Tested with the following result:
- Emptying log table works
- Emptying banduxer table works
- Emptying user_options works
- Emptying station_profile works

Not working:
- Emptying eQSL_images
- Emptying qsl_images

**Comment by phl0** [comment]
Confirmed. (e)qsl_images tables are now emptied as well.

**Comment by phl0** [comment]
Rest also tested. Deleting station_location removes connected data.
Removing single QSOs also removes relevant stuff from DB and file system. 
Good to go.

**Review by phl0 — APPROVED** [review]

**Pull request merged**
