### PR TITLE
QSO Edit Modal

### PR DESCRIPTION
**Pull request by HB9HIL**
Did a little refurbish of the QSO edit modal. The HTML was inconsistent and it looked a bit odd. 

In addition I added the ability to edit the Antenna Path which was requested in #987. We have this field in database, it gets imported from adif, so why not allow editing it.

### CODE REVIEW

**Review by phl0 — APPROVED** [review]
Works fine. Maybe add ANT_PATH to the displayQso or logbook/view popup to show that info if stored?

**Comment by HB9HIL** [comment]
> Works fine. Maybe add ANT_PATH to the displayQso or logbook/view popup to show that info if stored?

Good Point!!

**Comment by HB9HIL** [comment]
> Works fine. Maybe add ANT_PATH to the displayQso or logbook/view popup to show that info if stored?

I would do this in a second PR as this brings some other points up. (Distance Calculation and so on). Fine with that?
PS: Prop Mode is missing aswell :D

**Comment by phl0** [comment]
> > Fine with that?

Jupp

**Pull request merged**
