### PR TITLE
[GRIDMAP] Create a Gridmap based on Propagation Mode

### PR DESCRIPTION
**Pull request by HB9HIL**
telegram-cloud-photo-size-4-5893301618605146578-y

Comment: Looks quite heavy but the parameter is needed at alot places. At the moment I think everything is working, so ready 2 review

### CODE REVIEW

**Comment by HB9HIL** [comment]
found a bug and will try to make the ui more compact (feedback by @AndreasK79 )

**Review by AndreasK79 — APPROVED** [review]

**Comment by AndreasK79** [comment]
Works here, and more compact now :)

**Comment by phl0** [comment]
Works basically. But shows wrong data if Band is SAT and Prop Mode is EME for example:

image

**Comment by HB9HIL** [comment]
Shouldn't happen. Prop Mode select should be disabled if Band = SAT.

Please try empty your cache.

**Comment by HB9HIL** [comment]
@phl0  Issue is that your default band is set to 'SAT'. It's reproducable.
I will fix this issue later today.

**Comment by HB9HIL** [comment]
> @phl0 Issue is that your default band is set to 'SAT'. It's reproducable. I will fix this issue later today.

fix in #346

**Pull request merged**
