### PR TITLE
Satpass date

### PR DESCRIPTION
**Pull request by AndreasK79**
Added date so that you can run predictions on different dates:
image

Added TLE column to show if sat has TLE in sat table:
image

Added update button for TLE under debug (and cron job):
image

### CODE REVIEW

**Review by phl0 — CHANGES_REQUESTED** [review]
image

I'm sorry ... :D

**Review by phl0 — APPROVED** [review]
It works fine here.

**Review by int2001 — APPROVED** [review]
i like it.
perhaps add a `*` in one of the next PRs to plan the day by seeing all passes? :)

**Comment by phl0** [comment]
> i like it. perhaps add a `*` in one of the next PRs to plan the day by seeing all passes? :)

And maybe set default times to 00:00 and 24:00?

**Review by phl0 — APPROVED** [review]
Latest version running fine now.

**Pull request merged**
