### PR TITLE
Eqsl Password HTMLspecialchars

### PR DESCRIPTION
**Pull request by HB9HIL**
encode eqslpassword for the adif url

### CODE REVIEW

**Comment by HB9HIL** [comment]
tested with my existing password and atleast it does not break something.

**Review by int2001 — APPROVED** [review]
Tested with "old"-password and with a password containing a `'`. works

**Comment by HB9HIL** [comment]
Funfact:

Tested the password `test<test` 

Current `dev` branch -> works
This PR -> fails

So the issues must be located somewhere else in #695

**Comment by HB9HIL** [comment]
Finally found the issue. XSS clean encoded the password, We can safely decode it afterwards to use it for eQSL

**Pull request merged**
