### PR TITLE
fix callbook state data

### PR DESCRIPTION
**Pull request by HB9HIL**
in addition to #145 

this fixes the callbook state data for all available data

### CODE REVIEW

**Review by int2001 — APPROVED** [review]
Tested this. Works great. Even updating out of LBA is now working!
Not 100% sure about the new Logic at qrz.php L100/L103.

**Comment by HB9HIL** [comment]
@phl0 please check. just removed US dependency for state parameter

we need to merge this to test racecondition

**Comment by HB9HIL** [comment]
> Tested this. Works great. Even updating out of LBA is now working!
> 
> Not 100% sure about the new Logic at qrz.php L100/L103.

I added in Line 95

**Review by phl0 — APPROVED** [review]
Works as expected now.

**Pull request merged**
