### PR TITLE
Qrz state modified

### PR DESCRIPTION
**Pull request by HB9HIL**
After editing a QSO the new QRZ.com state is defined as "modified" in database "M"

we could show this also in the Log Tables to make clear that this QSO was modified and will be uploaded again.

image

### CODE REVIEW

**Review by int2001 — APPROVED** [review]
More transparency for the users.

**Comment by phl0** [comment]
Should we use another color here? IIRC yellow was used for another state already.

**Comment by int2001** [comment]
> Should we use another color here? IIRC yellow was used for another state already.

as far as i remember yellow is "re-upload". at classic-QSL it is "requested"

**Review by phl0 — APPROVED** [review]
Let's leave it like this then. Too many different colors also not the best idea :)

**Pull request merged**
