### PR TITLE
Maptile Settings in Global Options

### PR DESCRIPTION
**Pull request by HB9HIL**
As discussed in #714 and also in the early days of Wavelog, there were always the wish or necessarity to change the maptile server or specific configurations, like the subdomain system (a chinese maptile provider uses `1234` instead `abc`)

I would be happy if @violarulan could test this aswell

This PR brings a new point in the global options to change these configurations. There is one change in the leaflet.js where I replaced the hardcoded `abc` subdomain system with a variable. 

All Maps are tested. 
Static Map is tested.

You can test the option by setting the chinese map provider of autonavi

Maptiles Server URL
`https://webrd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x={x}&y={y}&z={z}`

Subdomain System of Maptile Server
`1234`

URL of the Copyright Source
`https://autonavi.com/` (probably not reachable from EU internet, but tileserver is reachable)

Name of the Copyright Source
`AutoNavi`

### CODE REVIEW

**Review by violarulan — APPROVED** [review]
Works as expected perfectly.

**Comment by HB9HIL** [comment]
I added a "Reset to default" Button to go back easily. Also I added a link to the Wiki where we can collect tested and working maptile Servers. 

I kindly ask @violarulan to complete the information for the chinese servers

Here: https://github.com/wavelog/wavelog/wiki/Maptile-Server

**Comment by HB9HIL** [comment]
> Works as expected perfectlly.

Thanks for the feedback

**Comment by AndreasK79** [comment]
Other than error the first time I enter the option (because no option exists), it's working.

**Comment by HB9HIL** [comment]
@AndreasK79 fixed

**Review by AndreasK79 — APPROVED** [review]

**Comment by hellofinch** [comment]
hello, this option does not work for me. Here is my config. And the map is blank.
image
image
After I reset to the default, the map shows up.
: )

**Comment by hellofinch** [comment]
Hello, maybe there is a bug.
After I set the new server and return to the dashboard, I need to force-refresh the page with `ctrl + F5`. Otherwise, the map is blank.

**Comment by HB9HIL** [comment]
This is related to the caching of your browser and normal behaviour :)

**Pull request merged**
