### PR TITLE
Show DXCC as badge with status in the search results

### PR DESCRIPTION
**Pull request by HB9HIL**
image

### CODE REVIEW

**Review by int2001 — CHANGES_REQUESTED** [review]
Searchbar is working, but at add QSO it throws an error:

image

**Comment by phl0** [comment]
> Searchbar is working, but at add QSO it throws an error:

And here is the fix: https://github.com/HB9HIL/wavelog/pull/116.

**Comment by phl0** [comment]
Other than that a nice idea. Tested ok with https://github.com/HB9HIL/wavelog/pull/116.

**Comment by HB9HIL** [comment]
tnx for the fix @phl0 

missed the method above

**Review by int2001 — APPROVED** [review]
works

**Pull request merged**
