### PR TITLE
Add None to DXCCs

### PR DESCRIPTION
**Pull request by int2001**
ADIF_DXCC = 0 was not part of the dxcc_entities table.

So a lot of Users skipped the step to fill in their own DXCC. As a result some exports weren't working (That was a bug).

This one adds the dxcc "None" hard to the DXCC-Table and forces the User to chose it's own DXCC

### CODE REVIEW

**Comment by int2001** [comment]
@HB9HIL could you pse add a check for the installer? i'm to stupid for that JS-Magic ;)

**Review by phl0 — APPROVED** [review]
Works fine so far.

**Review by AndreasK79 — APPROVED** [review]

**Comment by HB9HIL** [comment]
Just added a DXCC requirement to the installer

**Comment by HB9HIL** [comment]
PS: There is no DXCC "NONE" for /MM or /AM in the installer, as the callsign should always be the personal operator callsign without any pre- or suffixes. Therefor it always has a DXCC

**Pull request merged**
