### PR TITLE
some ideas for the Docker support

### PR DESCRIPTION
**Pull request by dg0tm**

### CODE REVIEW

**Comment by int2001** [comment]
Pipe needs to be adjusted as well

**Comment by int2001** [comment]
At this point everything is working.
Tested:
- Install
- index.php rewrite
- Ref-Downloads
- LoTW-Sync
- QSL-Image Download
- miscellaneous Awards

**Comment by int2001** [comment]
Yeah. tested this.
Everythings working.
much fewer layers / leaner Image. Well done.

Let's wait for #306 until merge, because cron will change with that PR

**Comment by int2001** [comment]
Just a marker here.
As mentioned in our call - `./application/cache` is missing rw for group.
Rest is fine

**Review by int2001 — APPROVED** [review]
Yeah. now it's perfect.

tested:
- All kind of user-generated data (eQSLs / QSLs)
- All kind of references (POTA, SOTA, Countryfiles and so on)
- master-cron
- ADIF Up/Down
- Caching-functionality for Bandmap/DXPeditions, etc.

works like a charm. thanks a lot for this one

**Comment by HB9HIL** [comment]
Thx to you guys :) @dg0tm @int2001  👍

**Pull request merged**
