### PR TITLE
[SimpleFLE] Fixed an issue at saving QSOs

### PR DESCRIPTION
**Pull request by HB9HIL**
It can happen that, if the network connection is slow, the SimpleFLE page gets cleared and reloaded before all QSOs were saved. Reason for that ins basically a bad code, which made one Ajax Call for each QSO (race-cond) 

I refactored that to send all qsos as json in ONE ajax call you the controller.

### CODE REVIEW

**Review by phl0 — CHANGES_REQUESTED** [review]
QSOs get saved into the DB but an (empty) error message:

image

**Comment by phl0** [comment]
I can provide the SFLE text via PM.

**Comment by AndreasK79** [comment]
Got the same here with the sample data.

**Comment by HB9HIL** [comment]
@phl0  and @AndreasK79 please test agn. Should be fixed

**Comment by AndreasK79** [comment]
@HB9HIL error is gone now :)

**Review by phl0 — APPROVED** [review]
Fix confirmed!

image

**Pull request merged**
