### PR TITLE
[Advanced Logbook] Only icons on some buttons

### PR DESCRIPTION
**Pull request by AndreasK79**
image
image

Only icons on search, option and delete. Added alt-text and hover-text on these buttons.

### CODE REVIEW

**Review by int2001 — APPROVED** [review]
you've my vote. i like.
lets wait for @phl0 and @HB9HIL

**Review by phl0 — APPROVED** [review]
Nice. This saves some more space on mobile platforms :)

Screenshot_20241129_131858_Firefox

**Comment by int2001** [comment]
Whooooot? No Mode, @phl0 :D #SCNR

**Comment by phl0** [comment]
> Whooooot? No Mode, @phl0 :D #SCNR

Could not decode your signal 8-)

**Pull request merged**
