### PR TITLE
Added Region to logging/edit

### PR DESCRIPTION
**Pull request by int2001**
Added the Region-Column to:
- Log QSO
- Edit QSO

Open:
Derivation logic for Region. Need tables/data from @dg0tm for that.

### CODE REVIEW

**Comment by AndreasK79** [comment]
@int2001 tested working on both QSO logging and editing!

2 things:
1: Sort dropdown
2: Display region when clicking on QSO

**Review by AndreasK79 — APPROVED** [review]

**Review by phl0 — CHANGES_REQUESTED** [review]
IMHO we should align the two lists:

Screenshot from 2024-12-24 00-20-06

Screenshot from 2024-12-24 00-20-33

**Review by phl0 — APPROVED** [review]
Ok for me now 👍

**Review by AndreasK79 — APPROVED** [review]

**Comment by phl0** [comment]
Maybe add short region in brackets? https://github.com/int2001/wavelog/pull/17

**Review by phl0 — APPROVED** [review]
👍👍

**Pull request merged**
