### PR TITLE
Test-PR for languages at Label-Feature

### PR DESCRIPTION
**Pull request by int2001**
Just checking the workflow for gettext at label-page.
Hope i did it right.

For @HB9HIL : I know, i used the generic kind for umlauts. (ue for ü) - it's because the PO-Files were not in UTF8-Mode on my machine. But this is only for testing-purposes

### CODE REVIEW

**Comment by HB9HIL** [comment]
You should use the script I provided in the chat because your way removed all the important filedata (comments of sourcecode line numbers) 

image

**Comment by int2001** [comment]
I used your script. Strange...

**Comment by HB9HIL** [comment]
Try again. This is the script which works:

```bash
xgettext --no-wrap -o assets/lang_src/messages.pot --copyright-holder=Wavelog --from-code=UTF-8 --keyword=__ --keyword=_ngettext:1,2 --keyword=_pgettext:1c,2 -L PHP $(find . -name "*.php")

for po in $(find . -name "*.po"); do
    msgmerge --no-wrap -UN --verbose "$po" assets/lang_src/messages.pot;
done

find . -name "*.po~" -delete

for po in $(find . -name "*.po"); do
    mo="${po%.po}.mo";
    msgfmt --verbose -o "$mo" "$po";
done
```

**Comment by int2001** [comment]
Ran the script (again) - it's the same.
no changes to commit.
or do i have to reset everything back to alpha, merge only the altered controller, adjust the langs, and run the script again?

**Comment by HB9HIL** [comment]
> Ran the script (again) - it's the same. no changes to commit. or do i have to reset everything back to alpha, merge only the altered controller, adjust the langs, and run the script again?

If I run the script on your branch it works. Try run it as shell script
[translation.sh.zip](https://github.com/user-attachments/files/15759382/translation.sh.zip)

**Comment by HB9HIL** [comment]
Probably a UTF-8 issue on your side. Nothing I can do about

**Comment by int2001** [comment]
No differences between the 1st and 2nd script:
```
diff ~/genpo_hil.sh ~/genpo_hil.sh
www-data ~>
```

Running it:
```
www-data ~> ~/genpo_hil.sh
...............................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 3.
................................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 15.
...................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 13.
.............................................................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 3.
......................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 4.
.......................................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 3.
...................................................................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 3.
...................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 3.
....................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 15.
...................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 3.
................................................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 24.
...................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 12.
.............................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 3.
.......................................................................................................................................................................................................
Read 1 old + 1 reference, merged 1762, fuzzied 0, missing 0, obsolete 3.
299 translated messages, 1462 untranslated messages.
919 translated messages, 842 untranslated messages.
501 translated messages, 1260 untranslated messages.
159 translated messages, 1602 untranslated messages.
148 translated messages, 1613 untranslated messages.
136 translated messages, 1625 untranslated messages.
69 translated messages, 1692 untranslated messages.
252 translated messages, 1509 untranslated messages.
752 translated messages, 1009 untranslated messages.
134 translated messages, 1627 untranslated messages.
870 translated messages, 891 untranslated messages.
714 translated messages, 1047 untranslated messages.
274 translated messages, 1487 untranslated messages.
158 translated messages, 1603 untranslated messages.
```

After that - no diff to this PR

**Comment by int2001** [comment]
locale was set properly. the problem was this one: https://askubuntu.com/a/778672

hpe everything is okay now.

**Comment by HB9HIL** [comment]
> locale was set properly. the problem was this one: https://askubuntu.com/a/778672
> 
> hpe everything is okay now.

The commit (https://github.com/wavelog/wavelog/compare/05cc5c982e2bf462ef196796ef0e64b43734383a..e7dbc9125aae8887199f8b294c2af0b5a92f4336) looks good but I think you screwed up the PR

image

**Comment by HB9HIL** [comment]
correction. does not look good. You did not fix the conflicts.

**Comment by int2001** [comment]
did you made an PR/commit in between? sorry - didn't know/didn't check. 
Just thought we/i'd should test if we can work with it.

i'll close the PR .

nevermind.

**Pull request closed without merging**
