### PR TITLE
[LBA] Added user options for map layers

### PR DESCRIPTION
**Pull request by AndreasK79**
By popular demand:
image

### CODE REVIEW

**Comment by abarrau** [comment]
Hello, 
i thinks that too yesterday, 
but can i propose an other way : save user option when user clic on checkbox map menu ?

**Review by phl0 — COMMENTED** [review]
There is an issue with the gridlines at least. I checked that box but after mapping the gridlines are missing. Deactivating and activating them on the map works however.

Screenshot from 2024-02-15 14-08-40

Screenshot from 2024-02-15 14-08-50

**Review by phl0 — APPROVED** [review]
Working fine now.

**Comment by AndreasK79** [comment]
> Hello, I think that too yesterday, but can i propose an other way : save user option when user click on checkbox map menu ?

Hi, That could be done, but I want to keep it under options. I also play with these layers, and I don't want to save the state after clicking on them.

**Pull request merged**
